---
# see https://github.com/nextapps-de/flexsearch#tokenizer-prefix-search for options
tokenizer: "full" # strict, forward, reverse, full
custom_domain: "https://sefanja.github.io/begrippenkader/"
fail_on_validation: false
searchableAttributes:
  - "prefLabel" # you should not delete this one
  - "notation"
  - "altLabel"
  - "hiddenLabel"
  - "example"
  - "definition"
ui:
  title: "Begrippenkaders | Netbeheer Nederland"
  logo: "logo.svg"
  colors:
    skoHubWhite: "rgb(255, 255, 255)"
    skoHubDarkColor: "rgb(0, 45, 65)"
    skoHubMiddleColor: "rgb(26, 66, 84)"
    skoHubLightColor: "rgb(77, 108, 122)"
    skoHubThinColor: "rgb(166, 182, 190)"
    skoHubBlackColor: "rgb(5, 30, 30)"
    skoHubAction: "rgb(0, 95, 135)"
    skoHubNotice: "rgb(250, 180, 50)"
    skoHubDarkGrey: "rgb(155, 155, 155)"
    skoHubMiddleGrey: "rgb(200, 200, 200)"
    skoHubLightGrey: "rgb(235, 235, 235)"
  fonts:
    regular:
      font_family: "Poppins"
      font_style: "normal"
      font_weight: 400
      name: "poppins-v24-latin-regular"
    bold:
      font_family: "Poppins"
      font_style: "normal"
      font_weight: 700
      name: "poppins-v24-latin-regular"
